spring:
  profiles:
    active: dev
  thymeleaf:
    check-template-location: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
kapok:
  api-package: com.fans.api
wechat:
  appid: wxb596d23b0c9f5dd2
  appsecret: ac919349bf19abdcd5c834c42a631a4a
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code